version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  deploy-to-gcp:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - gcp-cli/setup
      - run:
          name: Setup Service Account
          command: |
            echo "$GCLOUD_SERVICE_KEY" > /tmp/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
      - run:
          name: Configure Docker for GCR
          command: |
            gcloud auth configure-docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/catboost-api:$CIRCLE_SHA1 .
            docker push gcr.io/$GOOGLE_PROJECT_ID/catboost-api:$CIRCLE_SHA1
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy catboost-api \
              --image gcr.io/$GOOGLE_PROJECT_ID/catboost-api:$CIRCLE_SHA1 \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --port 8000

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy-to-gcp:
          filters:
            branches:
              only: main
           



