version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements/requirements.txt
      - run:
          name: Run tests
          command: |
            python -m pytest tests/ -v

  build-and-deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY
          google_project_id: GOOGLE_PROJECT_ID
      - run:
          name: Configure Docker for GCR
          command: |
            gcloud auth configure-docker
      - run:
          name: Build Docker image
          command: |
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/catboost-mlops:$CIRCLE_SHA1 .
            docker tag gcr.io/$GOOGLE_PROJECT_ID/catboost-mlops:$CIRCLE_SHA1 gcr.io/$GOOGLE_PROJECT_ID/catboost-mlops:latest
      - run:
          name: Push to Google Container Registry
          command: |
            docker push gcr.io/$GOOGLE_PROJECT_ID/catboost-mlops:$CIRCLE_SHA1
            docker push gcr.io/$GOOGLE_PROJECT_ID/catboost-mlops:latest
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy catboost-api \
              --image gcr.io/$GOOGLE_PROJECT_ID/catboost-mlops:$CIRCLE_SHA1 \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --port 8000 \
              --timeout 300 \
              --memory 2Gi \
              --cpu 1

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: main