version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  build_test_deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      
      # Setup GCP CLI without project_id argument
      - gcp-cli/setup:
          gcloud_service_key: GCLOUD_SERVICE_KEY
          google_compute_zone: GOOGLE_COMPUTE_ZONE
      
      # Set the project using gcloud command
      - run:
          name: Set GCP Project
          command: |
            gcloud config set project $GOOGLE_PROJECT_ID
      
      - run:
          name: Configure Docker for GCR
          command: |
            gcloud auth configure-docker
      
      - run:
          name: Build and push Docker image
          command: |
            docker build -f catboost_mlops_project/cat_mlops/Dockerfile -t catboost-mlops .
            docker tag catboost-mlops asia-northeast3-docker.pkg.dev/catboost-ml123/yugayv/catboost-ml-api:latest
            docker push asia-northeast3-docker.pkg.dev/catboost-ml123/yugayv/catboost-ml-api:latest
            # Deploy to Cloud Run
            gcloud run deploy catboost-ml-api \
      
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy catboost-ml-api \
              --image gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:$CIRCLE_SHA1 \
              --platform managed \
              --region asia-northeast3 \
              --allow-unauthenticated \
              --port 8000 \
              --memory 2Gi \
              --cpu 1

workflows:
  build_test_deploy:
    jobs:
      - build_test_deploy:
          filters:
            branches:
              only: main