version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  deploy-to-gcp:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      
      # Create and setup service account key file
      - run:
          name: Setup Service Account Key
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/gcloud-service-key.json
            gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
      
      - run:
          name: Configure Docker for GCR
          command: |
            gcloud auth configure-docker
      
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:$CIRCLE_SHA1 .
            docker push gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:$CIRCLE_SHA1
      
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy catboost-ml-api \
              --image gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:$CIRCLE_SHA1 \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --port 8000 \
              --memory 2Gi \
              --cpu 1

workflows:
  deploy-workflow:
    jobs:
      - deploy-to-gcp:
          filters:
            branches:
              only: main