version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  deploy-to-gcp:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - gcp-cli/setup:
          version: latest
      - run:
          name: Setup service account (Direct JSON method)
          command: |
            # Store the service account key directly as JSON
            echo '$GCLOUD_SERVICE_KEY' > /home/circleci/gcloud-service-key.json
            
            # Verify the JSON file was created correctly
            echo "Service account file size: $(wc -c < /home/circleci/gcloud-service-key.json)"
            
            # Activate service account
            gcloud auth activate-service-account --key-file /home/circleci/gcloud-service-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
      - run:
          name: Configure Docker for GCR
          command: |
            gcloud auth configure-docker
      - run:
          name: Build and push Docker image
          command: |
            cd catboost_mlops_project/cat_mlops
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:latest .
            docker push gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:latest
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy catboost-ml-api \
              --image gcr.io/$GOOGLE_PROJECT_ID/catboost-ml-api:latest \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --port 8000

workflows:
  deploy-workflow:
    jobs:
      - deploy-to-gcp:
          filters:
            branches:
              only: main
                - [Cloud Run API](https://console.developers.google.com/apis/api/run.googleapis.com/overview?project=catboost-ml123)
                - [Container Registry API](https://console.developers.google.com/apis/api/containerregistry.googleapis.com/overview?project=catboost-ml123)
                - [Cloud Build API](https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=catboost-ml123)
                - [Cloud Storage API](https://console.developers.google.com/apis/api/storage.googleapis.com/overview?project=catboost-ml123)
                - [Cloud Storage File Store API](https://console.developers.google.com/apis/api/storage-component.googleapis.com/overview?project=catboost-ml123)
           



