# Package Overview
app_config:
  package_name: catboost_model
  training_data_file: Dataset.csv
  test_data_file: test_data.csv
  pipeline_save_file: catboost_pipeline

# Model Parameters
ml_model_config:
  target: FIN_JGMT
  features:
    - DV_R
    - DA_R
    - AV_R
    - AA_R
    - PM_R
  test_size: 0.2
  random_state: 42
  n_estimators: 1000
  learning_rate: 0.1
  depth: 6
  l2_leaf_reg: 3
  border_count: 128
  thread_count: -1
